//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seedsfromzion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("seedsfromzion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap addOrder_48 {
            get {
                object obj = ResourceManager.GetObject("addOrder_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*The background of the page , something green*/
        ///.sign {width:100%;
        ///	color:black}
        ///body
        ///{
        ///background-color:white;
        ///}
        ////*headings will be a color close to white*/
        ///.signature { color:black ; font-size:12px; font-family:&quot;Times New Roman&quot;, Times, serif;}
        ///p { color:black;}
        ///.line {color: black; height: 1px;}
        ///.maintable {color:black; border: 1px solid black; border-collapse:collapse;}
        ///td {padding:15px; border: 1px solid black;}
        ///th {background-color:black; color:white; border: 1px solid black;}
        ///.tdsign{  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blackAndWhiteStyle {
            get {
                return ResourceManager.GetString("blackAndWhiteStyle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Flower_add3 {
            get {
                object obj = ResourceManager.GetObject("Blue_Flower_add3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Flower_delete {
            get {
                object obj = ResourceManager.GetObject("Blue_Flower_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*The background of the page , something green*/
        ///.sign {width:100%;
        ///	color:black}
        ///body
        ///{
        ///background-color:#f4ffd8;
        ///}
        ////*headings will be a color close to white*/
        ///.signature { color:green ; font-size:12px; font-family:&quot;Times New Roman&quot;, Times, serif;}
        ///p { color:black;}
        ///.line {color: #f00; height: 1px;}
        ///.maintable {color:black; border: 1px solid black; border-collapse:collapse;}
        ///td {padding:15px; border: 1px solid green;}
        ///th {background-color:green; color:white; border: 1px solid green;}
        ///.tdsign{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colorStyle {
            get {
                return ResourceManager.GetString("colorStyle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete40_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("delete40_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Download_32_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Download_32_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emd438_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("emd438_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Favorites22_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Favorites22_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap File_html_alt_48 {
            get {
                object obj = ResourceManager.GetObject("File_html_alt_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindOrder {
            get {
                object obj = ResourceManager.GetObject("FindOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flowers {
            get {
                object obj = ResourceManager.GetObject("Flowers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HoursUpdate_482 {
            get {
                object obj = ResourceManager.GetObject("HoursUpdate_482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Money_56_wide {
            get {
                object obj = ResourceManager.GetObject("Money_56_wide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap percent_graph {
            get {
                object obj = ResourceManager.GetObject("percent_graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap percent_graph_infridge {
            get {
                object obj = ResourceManager.GetObject("percent_graph_infridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap percent_graph_time {
            get {
                object obj = ResourceManager.GetObject("percent_graph_time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap percent_graph_type1 {
            get {
                object obj = ResourceManager.GetObject("percent_graph_type1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Plant_64 {
            get {
                object obj = ResourceManager.GetObject("Plant_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap postage_stamp_48 {
            get {
                object obj = ResourceManager.GetObject("postage_stamp_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer42_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Printer42_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrintHS {
            get {
                object obj = ResourceManager.GetObject("PrintHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refrigerator_56 {
            get {
                object obj = ResourceManager.GetObject("Refrigerator_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removeOrder {
            get {
                object obj = ResourceManager.GetObject("removeOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salesGraph {
            get {
                object obj = ResourceManager.GetObject("salesGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save16_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Save16_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings_32_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Settings_32_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Upload_32_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Upload_32_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserAdd_48 {
            get {
                object obj = ResourceManager.GetObject("UserAdd_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserEnter_42_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("UserEnter_42_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserRemove_48 {
            get {
                object obj = ResourceManager.GetObject("UserRemove_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users42_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("Users42_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UsersCreate_Layer_1 {
            get {
                object obj = ResourceManager.GetObject("UsersCreate_Layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UsersDelete_Layer_11 {
            get {
                object obj = ResourceManager.GetObject("UsersDelete_Layer_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
